journal/eval/urls.py
from django.urls import path

from . import views

app_name = "eval"

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path("notes_by_student/", views.notes_by_student, name="notes_by_student"),
    path(
        "get_notes_by_student/<int:student_id>/",
        views.get_notes_by_student,
        name="get_notes_by_student",
    ),

]

journal/journal/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('eval.urls')),
    path('admin/', admin.site.urls),
]

journal/eval/models.py
from django.db import models
import datetime
from django.utils import timezone


class Formateur(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    def __str__(self):
        return (f"{self.first_name} {self.last_name}")



class Student(models.Model):
    first_name_student = models.CharField(max_length=200)
    last_name_student = models.CharField(max_length=200)

    def __str__(self):
        return (f"{self.first_name_student} {self.last_name_student}")


class Note(models.Model):
    author = models.ForeignKey(Formateur,on_delete=models.CASCADE)
    subjet = models.CharField(max_length=200)
    notes = models.TextField(max_length=200)
    date = models.DateField('date published')
    students = models.ManyToManyField(Student)

    def __str__(self):
        return f"De {self.author} : {self.subjet} {self.students}"

journal/eval/views.py
from django.http import JsonResponse
from django.shortcuts import render

from .models import Student


def serialize_note(note):

    students = []
    for student in note.students.all():
        students.append(str(student))

    return {
        "id": note.id,
        "author": str(note.author),
        "subjet": note.subjet,
        "notes": note.notes,
        "date": note.date,
        "students": students,
    }


def accueil(request):
    return render(request, "eval/accueil.html")


def notes_by_student(request):
    students = Student.objects.all()
    context = {
        "students": students,
    }
    return render(request, "eval/notes_by_student.html", context)


def get_notes_by_student(request, student_id):
    student = Student.objects.get(pk=student_id)
    student_notes = student.note_set

    data = []

    for note in student_notes.all():
        data.append(serialize_note(note))

    return JsonResponse(data, safe=False)

journal/eval/templates/eval/accueil.html
{% extends 'index.html' %}
{% block content %}
<div style="background-color: red;">
    <h1 align="center" style="color: white;">Journal de bord</h1>
    <p align="center" style="color: white;" style="font-weight: bold;" style="font-size: large;">Bienvenue sur le journal de bord de l'équipage Simplon 🏂</p> 
    
</div>

{% endblock %}

journal/eval/templates/eval/notes_by_student.html
{% extends 'index.html' %}

{% block javascript %}
  <script>
    $("#select_student").change(function () {
      var student_id = $(this).val();
      console.log(student_id)
      if (student_id != "none"){
        $.ajax({
          url: "/get_notes_by_student/" + student_id + "/",
          dataType: 'json',
          success: function (data) {
            $("#student_notes").empty()
            console.log(JSON.stringify(data))
            data.forEach((note) => {
              var str_students = "";
              note.students.forEach((student) => {
                str_students += student + " "
              })
              $("#student_notes").append(
                "<h2>" + note.subjet + "<small> - By " + note.author + " on " + note.date + "</small>" + "</h2>",
                "<br> About: " + str_students + ":",
                "<p>" + note.notes,
                "<hr>"
              )
            });
          }
        });
      }
    });
  </script>
{% endblock %}

{% block content %}
    <label for="students">Select a student</label>
    <select name="students" id="select_student">
        <option value="none" selected>---</option>
        {% for student in students %}
        <option value="{{ student.id }}">{{ student.first_name_student }} {{ student.last_name_student }}</option>
        {% endfor %}
    </select>
    <div id="student_notes">
    </div>
{% endblock %}

journal/eval/templates/index.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="stylesheet.css">
    <title>Le Journal de bord de Simplon</title>
</head>
<body>
    <nav>
      <img src="https://www.est-ensemble.fr/sites/default/files/styles/large_slider/public/logo_simplon_simple_red1.png?itok=J7wPlX1N" style="height: 50px;">
      <a href="{% url 'eval:accueil' %}">Accueil</a> |
      <a href="{% url 'eval:notes_by_student' %}">Notes by student</a>
    </nav>
   
    <hr>
    {% block content %}
    {% endblock %}
    <hr>
    
    <footer>
      This is the footer
    </footer>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    {% block javascript %}{% endblock %}
</body>
</html>